//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40607.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Prager_Pricing_Program.Properties {
    using System;
    using System.IO;
    using System.Resources;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the Strongly Typed Resource Builder
    // class via a tool like ResGen or Visual Studio.NET.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    class Resources {
        
        private static System.Resources.ResourceManager _resMgr;
        
        private static System.Globalization.CultureInfo _resCulture;
        
        /*FamANDAssem*/ internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if ((_resMgr == null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Prager_Pricing_Program.Properties.Resources", typeof(Resources).Assembly);
                    _resMgr = temp;
                }
                return _resMgr;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return _resCulture;
            }
            set {
                _resCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap back {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("back", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap banner {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("banner", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Broom {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Broom", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Door1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Door1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap forward {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("forward", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap home {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("home", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap new10 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("new10", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap printer {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("printer", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Search {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Search", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap stopsign {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("stopsign", _resCulture)));
            }
        }
    }
}
